# Generated by Django 2.1.7 on 2019-04-16 20:51

from django.db import migrations, models
import menus.models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='image',
            field=models.ImageField(null=True, upload_to=menus.models.meal_image_file_path),
        ),
    ]
